### ISSUE TITLE
config.js not overridden

### ISSUE THREAD

**Issue by gotterdemarung** [dockerfile/ghost#2] opened 2014-02-13 07:58 UTC
Manual says:

> where `<override-dir>` is an absolute path of a directory that could contain:
> - `config.js`: custom config file copied from [here](https://github.com/TryGhost/Ghost/blob/master/config.example.js) (you must replace `127.0.0.1` with `0.0.0.0`)

But you can create/remove/make invalid this file in `<override-dir>` because it is ignored by ghost and docker's startup script

Confirmation:
- create&run new container
- open blog page from it
- open any blog entry
- link to homepage, located at the top of entry's page, will always point to `my-ghost-blog.com`, regardless to `config.js` in override dir

**Comment by EpocSquadron** [comment] 2014-02-15 21:23
This is essentially the same issue as #1.

**Comment by pilwon** [comment] 2014-02-15 21:54
- Duplicate of #1
- Fixed with PR contributed by @EpocSquadron

**Closed as completed by pilwon** 2014-02-15 21:54 UTC
